version: 0.1

phases:
  build:
    commands:
      - chmod +x atompub
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker build -t xtracdev/atompub:latest -t xtracdev/atompub:`cat buildNo` .
      - docker push xtracdev/atompub
