version: '2'

services:
  atomfeedpub:
    image: xtracdev/atompub
    ports:
      - "4000:8000"
    environment:
      - LINKHOST=${LINKHOST}
      - LISTENADDR=${LISTENADDR}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SVC=${DB_SVC}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CERTIFICATE=${CERTIFICATE}
      - CACERT=${CACERT}
    volumes:
      - ./atompubcerts:/certs

  nginxproxy:
    image: xtracdev/nginxproxy
    volumes:
      - ./rp.conf:/etc/nginx/nginx.conf
      - ./nginx-certs:/tmp/certs
    ports:
      - "5000:5000"
    depends_on:
      - "atomfeedpub"