version: '2'

services:
  atomfeedpub:
    image: xtracdev/atompub
    ports:
      - "4000:8000"
    environment:
      - LINKHOST=${LINKHOST}
      - LISTENADDR=${LISTENADDR}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SVC=${DB_SVC}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CERTIFICATE=${CERTIFICATE}
      - CACERT=${CACERT}
      - STATSD_ENDPOINT=${STATSD_ENDPOINT}
    volumes:
      - ./atompubcerts:/certs

  nginxproxy:
    image: xtracdev/nginxproxy
    volumes:
      - ./rp.conf:/etc/nginx/nginx.conf
      - ./nginx-certs:/tmp/certs
    ports:
      - "5000:5000"
    depends_on:
      - "atomfeedpub"

  logspout:
    image: raychaser/logspout-http:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - LOGSPOUT=ignore
      - SUMO_HTTP_TOKEN=${SUMO_HTTP_TOKEN}
      - HTTP_PROXY=${HTTP_PROXY}
      - DEBUG=1
    command: https://endpoint1.collection.us2.sumologic.com?http.path=/receiver/v1/http/$SUMO_HTTP_TOKEN\&http.proxy=$HTTP_PROXY\&http.gzip=true\&http.crash=false

  syslog:
    image: factorish/syslog
    ports:
      - 1515:514/udp
    entrypoint: /usr/bin/syslog -t udp
